import fs from "node:fs";
const h = fs.readFileSync("out/en/index.html", "utf8");
console.log("HTML total:", (h.length / 1024).toFixed(0), "KB");
let flight = 0;
for (const m of h.matchAll(/<script>self\.__next_f[\s\S]*?<\/script>/g)) flight += m[0].length;
console.log("RSC flight payload:", (flight / 1024).toFixed(0), "KB");
const style = h.match(/<style[^>]*>[\s\S]*?<\/style>/g) || [];
let css = 0;
for (const s of style) css += s[0].length;
console.log("inline <style> blocks:", style.length, (css / 1024).toFixed(0), "KB");
const imgs = h.match(/data:image\/webp[^"]*/g) || [];
console.log("hero data-URI:", (imgs[0]?.length || 0) / 1024, "KB");
const fonts = h.match(/data:font\/woff2[^)]*/g) || [];
let fb = 0;
for (const f of fonts) fb += f.length;
console.log("font data-URIs:", fonts.length, (fb / 1024).toFixed(0), "KB");
const scripts = h.match(/<script[^>]*>[\s\S]*?<\/script>/g) || [];
let sb = 0;
for (const s of scripts) sb += s.length;
console.log("all inline scripts:", scripts.length, (sb / 1024).toFixed(0), "KB (incl. flight)");